name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        name: tests
        runs-on: ubuntu-latest

        steps:
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: "1.20"
            
            - name: Check out code
              uses: actions/checkout@v3

            - name: Run tests
              run: go test -cover ./...

            - name: Install gosec
              run: go install github.com/securego/gosec/v2/cmd/gosec@latest

            - name: Run static security checks
              run: gosec ./...
    
    style:
        name: formatting
        runs-on: ubuntu-latest

        steps:
          - name: Set up Go
            uses: actions/setup-go@v4
            with:
              go-version: "1.20"
          
          - name: Check out code
            uses: actions/checkout@v3

          - name: Check formatting
            run: test -z $(go fmt ./...)

          - name: Install staticcheck
            run: go install honnef.co/go/tools/cmd/staticcheck@latest

          - name: Lint with staticcheck
            run: test -z $(staticcheck ./...)